### make sure that you have modified the GENERATION_MODEL, GENERATION_MODEL_TEST
GENERATION_MODEL="gaussian-splatting"
# GENERATION_MODEL="mip-splatting"
# GENERATION_MODEL="Compact-3DGS"
# GENERATION_MODEL="ges-splatting"
# GENERATION_MODEL="Scaffold-GS"
# GENERATION_MODEL="GS-IR"

RECONSTRUCTION_MODEL="gaussian-splatting"
# RECONSTRUCTION_MODEL="mip-splatting"
# RECONSTRUCTION_MODEL="Compact-3DGS"
# RECONSTRUCTION_MODEL="ges-splatting"
# RECONSTRUCTION_MODEL="Scaffold-GS"
# RECONSTRUCTION_MODEL="GS-IR"

REPRESENTATION=$RECONSTRUCTION_MODEL"_gre"
# REPRESENTATION=$RECONSTRUCTION_MODEL"_noise"
# REPRESENTATION=$RECONSTRUCTION_MODEL"_frequency"
# REPRESENTATION=$RECONSTRUCTION_MODEL"_rgb"

DATASET="tandt"
# DATASET="mip_nerf"

EXP_NAME=$DATASET"_"$GENERATION_MODEL"_"$REPRESENTATION

CKPT="/home/jamesyoung0623/rendering_deepfake/data/exp/$EXP_NAME/ckpt/model_epoch_best.pth"

GENERATION_MODEL_TEST="gaussian-splatting"
# GENERATION_MODEL_TEST="mip-splatting"
# GENERATION_MODEL_TEST="Compact-3DGS"
# GENERATION_MODEL_TEST="ges-splatting"
# GENERATION_MODEL_TEST="Scaffold-GS"
# GENERATION_MODEL_TEST="GS-IR"

DATASET_TEST="tandt"
# DATASET_TEST="mip_nerf"
DATASETS_TEST=$DATASET_TEST"_"$GENERATION_MODEL_TEST"_"$REPRESENTATION

CUDA_VISIBLE_DEVICES=1 python test.py --gpus 1 --ckpt $CKPT --exp_name $EXP_NAME datasets_test $DATASETS_TEST